### ISSUE TITLE
Can rules configuration support GEOSITE?

### ISSUE THREAD

**Issue by vimt** [Watfaq/clash-rs#441]
GEOSITE file are easy to use. it only need to write one geosite file url instead of write a lot of rule-providers.

For example, clash-meta config: 

```yaml
geox-url:
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"

rules:
  - GEOSITE,category-ads-all,DENY
  - GEOSITE,private,DIRECT
  - GEOSITE,paypal,AUTO
  - GEOSITE,youtube,AUTO
  - GEOSITE,google,AUTO
  - GEOSITE,twitter,AUTO
  - GEOSITE,pixiv,AUTO
  - GEOSITE,category-scholar-!cn,AUTO
  - GEOSITE,biliintl,AUTO
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,AUTO
  - GEOSITE,cn,DIRECT
```

Is there any plan to support this feature?
