### ISSUE TITLE
Can TUN mode supports DNS hijacking

### ISSUE THREAD

**Issue by Maasea** [Watfaq/clash-rs#590]
I'm using TUN mode on window, but all requests are sent as IPs, which invalidates the domain rule.

In TUN mode it is not possible to access the url through the proxy. I don't know if it's because TUN mode can't resolve the IP of the proxy server.
```
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  nameserver:
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.2/16

tun:
  enable: true
  device-id: "dev://Clash"
  route-all: true
```
Also, is it possible to manually disable the warning `simple-obfs is deprecated`, which is shown in the log every time a proxy request is used.
