### ISSUE TITLE
[feature] add a `checksum` file to help updater validate the download content

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#597]
FYI Github have removed the `md5` signature header. Ref: https://github.com/orgs/community/discussions/23512#discussioncomment-10013377

So, we should upload a checksum file, `.sha256` etc, to make the integrity of file checkable.

For example, we can do it in ci:
```yaml
- name: Calc the archive signature
        shell: pwsh
        run: Get-FileHash nyanpasu-service-${{ matrix.profile.target }}.zip -Algorithm SHA256 | Format-List > nyanpasu-service-${{ matrix.profile.target }}.zip.sha256
```

```yaml
 - name: Calc the archive signature
        run: sha256sum nyanpasu-service-${{ matrix.profile.target }}.tar.gz > nyanpasu-service-${{ matrix.profile.target }}.tar.gz.sha256
```

Ref: https://github.com/libnyanpasu/nyanpasu-service/blob/main/.github/workflows/build.yml

Maybe I can draft a pr to solve it later.
