### ISSUE TITLE
rule-provider在classic行为模式下的处理逻辑

### ISSUE THREAD

**Issue by chenzhiwei** [Watfaq/clash-rs#602]
## 配置文件

* config.yaml
```
mixed-port: 7890
mode: rule

dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5

proxies:
  - name: ss1
    type: ss
    server: 10.0.0.13
    port: 8388
    cipher: aes-256-gcm
    password: "password"
    udp: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - ss1

rule-providers:
  proxy-rules:
    type: file
    behavior: classical
    path: rules/proxy.yaml

rules:
  - GEOIP,CN,DIRECT
  - RULE-SET,proxy-rules,PROXY
  - MATCH,DIRECT
```
* rules/proxy.yaml
```
payload:
  - DOMAIN-SUFFIX,t.me
  - IP-CIDR,149.154.0.0/16
  - DOMAIN-SUFFIX,git.io
```

## 代理行为不符合预期

1. 以上配置不变的情况下，访问`t.me`会命中ruleset从而走代理，原因是`t.me`被解析到了`ip cidr 149.154.0.0/16`网段；而`git.io`却不走代理，因为其解析后的IP没命中rulset。看样子像是按域名解析后的IP来判断是否走代理的。
2. 将config.yaml中的`GEOIP,CN,DIRECT`去掉后，行为符合预期。

## 说明

我的rule规则本意是：

1. 当一个请求一个域名时，如果其解析出来的IP地址为GEOIP CN时，直连；
2. 当该域名解析出来的IP不是GEOIP CN时，继续使用后面的规则处理；
3. 如果后面的规则中规定该域名走代理时，那么就走代理；
4. 如果该域名没命中任何规则，则走到 MATCH,DIRECT；
