### ISSUE TITLE
start error: dns error: proto error: io error: no nameservers found in config since 0.3.1 linux

### ISSUE THREAD

**Issue by smoothdvd** [Watfaq/clash-rs#618]
Try from 0.3.1 to latest, clash-x86_64-unknown-linux-*

report "start error: dns error: proto error: io error: no nameservers found in config" after run the program

but 0.3.0 is working in the same config.yaml

My system info is

Linux 6.10.11-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Sep 26 03:28:26 UTC 2024 x86_64 GNU/Linux
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        24.1.0
Codename:       Xahea

**Comment by ibigbug** [comment]
Put your config please

**Comment by smoothdvd** [comment]
test with clash/tests/data/config/rules.yaml

```
---
port: 8888
socks-port: 8889
mixed-port: 8899
tproxy-port: 8900

tun:
  enable: false
  device-id: "dev://utun1989"
  route-all: false
  gateway: "198.19.0.1/32"
  so-mark: 3389
  # routes:
  #   - 0.0.0.0/1
  #   - 128.0.0.0/1

ipv6: true

dns:
  enable: true
  ipv6: true
  listen:
    udp: 127.0.0.1:53553
    tcp: 127.0.0.1:53553
    dot:
      addr: 127.0.0.1:53554
      ca-cert: dns.crt
      ca-key: dns.key
    doh:
      addr: 127.0.0.1:53555
      ca-cert: dns.crt
      ca-key: dns.key
      hostname: dns.example.com
    doh3:
      addr: 127.0.0.1:53555
      ca-cert: dns.crt
      ca-key: dns.key
      hostname: dns.example.com
        
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: normal
  fake-ip-range: 198.18.0.2/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    # - 114.114.114.114 # default value
    # - 1.1.1.1#auto # default value
    - tls://1.1.1.1:853#auto # DNS over TLS
#    - dhcp://en0 # dns from dhcp

allow-lan: true
mode: rule
log-level: trace
external-controller: :9090
external-ui: "public"
# secret: "clash-rs"
experimental:
  ignore-resolve-fail: true

asn-mmdb: Country-asn.mmdb

profile:
  store-selected: true
  store-fake-ip: false


proxy-groups:
  - name: "relay"
    type: relay
    proxies:
      - "plain-vmess"
      - "ws-vmess"
      - "ss-simple"
      - "trojan"
      - "auto"
      - "fallback-auto"
      - "load-balance"
      - "select"
      - "wg"
      - DIRECT

  - name: "udp-relay"
    type: relay
    proxies:
      # - "plain-vmess"
      - "ws-vmess"
      # - "h2-vmess"
      # - "tls-vmess"
      # - "grpc-vmess"
      - "ss-simple"
      # - "trojan"
      # - "auto"
      # - "fallback-auto"
      # - "load-balance"
      # - "select"
      # - "wg"
      # - DIRECT
  
  
  - name: "relay-one"
    type: relay
    use:
      - "file-provider"

  - name: "auto"
    type: url-test
    use:
      - "file-provider-uot"
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: "fallback-auto"
    type: fallback
    use:
      - "file-provider-uot"
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: "load-balance"
    type: load-balance
    use:
      - "file-provider-uot"
    proxies:
      - DIRECT
    strategy: round-robin
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: select
    type: select
    use:
      - "file-provider-uot"

  - name: test 🌏
    type: select
    use:
      - "file-provider"
    proxies:
      - DIRECT

proxies:
  - name: plain-vmess
    type: vmess
    server: 10.0.0.13
    port: 16823
    uuid: b831381d-6324-4d53-ad4f-8cda48b30811
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    connect-via: auto

  - name: ws-vmess
    type: vmess
    server: 10.0.0.13
    port: 16824
    uuid: b831381d-6324-4d53-ad4f-8cda48b30811
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /api/v3/download.getFile
      headers:
        Host: www.amazon.com

  - name: tls-vmess
    type: vmess
    server: 10.0.0.13
    port: 8443
    uuid: 23ad6b10-8d1a-40f7-8ad0-e3e35cd38297
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    tls: true

  - name: h2-vmess
    type: vmess
    server: 10.0.0.13
    port: 8444
    uuid: b831381d-6324-4d53-ad4f-8cda48b30811
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    tls: true
    network: h2
    h2-opts:
      path: /ray

  - name: grpc-vmess
    type: vmess
    server: 10.0.0.13
    port: 19443
    uuid: b831381d-6324-4d53-ad4f-8cda48b30811
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: abc

  - name: "ss-simple"
    type: ss
    server: 10.0.0.13
    port: 8388
    cipher: aes-256-gcm
    password: "password"
    udp: true

  - name: "trojan"
    type: trojan
    server: 10.0.0.13
    port: 9443
    password: password1
    udp: true
    # sni: example.com # aka server name
    alpn:
      - h2
      - http/1.1
    skip-cert-verify: true

  - name: "trojan-grpc"
    type: trojan
    server: 10.0.0.13
    port: 19443
    password: password1
    udp: true
    # sni: example.com # aka server name
    alpn:
      - h2
    skip-cert-verify: true
    network: grpc
    grpc-opts:
      grpc-service-name: def

  - name: "wg"
    type: wireguard
    server: engage.cloudflareclient.com
    port: 2408
    private-key: uIwDn4c7656E/1pHkJu23ZOe/4SuCnL+vL+jE2s4MHE=
    ip: 172.16.0.2/32
    ipv6: 2606:4700:110:8e5e:fa1:3f30:c077:e17c/128
    public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
    allowed-ips: ['0.0.0.0/0', '::/0']
    remote-dns-resolve: true
    dns:
      - 1.1.1.1
    udp: true

proxy-providers:
  file-provider:
    type: file
    path: ./ss.yaml
    interval: 300
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  file-provider-uot:
    type: file
    path: ./uot.yaml
    interval: 300
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

rule-providers:
  file-provider:
    type: file
    path: ./rule-set.yaml
    interval: 300
    behavior: domain

rules:
  - IP-CIDR,1.1.1.1/32,udp-relay
  - IP-CIDR,8.8.8.8/32,udp-relay
  - DOMAIN,google.com,ws-vmess
  - DOMAIN-KEYWORD,httpbin,trojan-grpc
  - DOMAIN,ipinfo.io,DIRECT
#  - RULE-SET,file-provider,trojan
  - GEOIP,CN,relay
  - DOMAIN-SUFFIX,facebook.com,REJECT
  - DOMAIN-KEYWORD,google,grpc-vmess
  - DOMAIN,google.com,select
  - SRC-IP-CIDR,192.168.1.1/24,DIRECT
  - GEOIP,CN,DIRECT
  - IP-CIDR,10.0.0.11/32,DIRECT
  - DST-PORT,53,ws-vmess
  - SRC-PORT,7777,DIRECT
  - MATCH, DIRECT
...
```
