### ISSUE TITLE
Feature Request: Support inline rules in rule-providers

### ISSUE THREAD

**Issue by 821869798** [Watfaq/clash-rs#795]
Please support rule-providers for inline mode
For example :
```yaml
rule-providers:
  google:
    type: inline
    behavior: domain
    payload:
      - '+.google.com'
  ```
